name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "keymap_drawer.config.yaml"
      - ".github/workflows/draw-keymaps.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      west_config_path: "config"
      json_path: "keymap-drawer/no-such-dir"
      amend_commit: false
      fail_on_error: false
      parse_args: "roBa:'-c 10 --layer-names default_win arrow_win default_mac arrow_mac mouse scroll bluetooth symbol num'"
